project:
  type: book
  output-dir: docs

book:
  title: GeoNotas
  subtitle: Ejemplos de procesamiento de datos espaciales
  reader-mode: true
  cover-image: cover.png
  favicon: cover.png
  site-url: https://geonotas.github.io
  repo-url: https://github.com/geonotas/geonotas.github.io

  chapters:
    - index.qmd

format:
  html:
    lang: es
    theme: cosmo
    code-link: true
