project:
  type: book
  output-dir: docs

book:
  title: GeoNotas
  subtitle: Ejemplos de procesamiento de datos espaciales
  reader-mode: true
  cover-image: logo-geonotas.png
  favicon: logo-geonotas.png
  site-url: https://geonotas.github.io
  repo-url: https://github.com/geonotas/geonotas.github.io

  chapters:
    - index.qmd

    - part: informacion-datos.qmd
      chapters:
        - informacion-datos-gdal.qmd    

format:
  html:
    lang: es
    theme: 
      - cosmo
      - geonotas.scss
    code-link: true